import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Card, Select, Button, Row, Col, Typography, message, Empty, Spin, List, Tag, Tooltip } from 'antd';
import { SaveOutlined, UndoOutlined, RedoOutlined, AimOutlined, DeleteOutlined } from '@ant-design/icons';
import { useCompositionStore } from '../../stores/useCompositionStore';
import { useAssetStore } from '../../stores/useAssetStore';
import { useProjectStore } from '../../stores/useProjectStore';
import { useInstanceStore } from '../../stores/useInstanceStore';
import { computeLayers } from '../../utils/layerMatcher';
import { InteractiveCanvas } from './InteractiveCanvas';
import { InstanceConfig, CompositionInput } from '@ac-gen/shared';
import { useHistory } from '../../hooks/useHistory';

const { Title, Text } = Typography;
const { Option } = Select;

export const InstanceFineTuner: React.FC = () => {
  const { generatedVariants, selectedProjectId } = useCompositionStore();
  const { products, decorations } = useAssetStore();
  const { projects } = useProjectStore();
  const { instances, fetchInstances, upsertInstance, loading } = useInstanceStore();

  const [selectedVariantKey, setSelectedVariantKey] = useState<string | null>(null);
  
  // Use history hook for undo/redo
  const { 
    state: currentConfig, 
    setState: setCurrentConfig, 
    undo, 
    redo, 
    canUndo, 
    canRedo,
    reset: resetHistory 
  } = useHistory<InstanceConfig | null>(null);

  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
  const [selectedLayerId, setSelectedLayerId] = useState<string | null>(null);

  // Bind keyboard shortcuts for undo/redo
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'z') {
        if (e.shiftKey) {
          redo();
        } else {
          undo();
        }
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [undo, redo]);

  const currentProject = useMemo(() => 
    projects.find(p => p.id === selectedProjectId) || 
    projects.find(p => p.projectName === selectedProjectId), 
  [projects, selectedProjectId]);

  useEffect(() => {
    if (selectedProjectId) {
      fetchInstances(selectedProjectId);
    }
  }, [selectedProjectId, fetchInstances]);

  // Handle Variant Selection
  const handleVariantSelect = (key: string) => {
    setSelectedVariantKey(key);
    const variant = generatedVariants.find(v => getVariantKey(v) === key);
    if (!variant || !selectedProjectId) return;

    // Find existing config or create new draft
    const existing = instances.find(i => 
      i.projectId === selectedProjectId &&
      i.productId === variant.productId &&
      i.energyLevel === variant.energyLevel &&
      i.capacityCode === variant.capacityCode
    );

    const newConfig = existing ? existing : {
      id: '', // Will be generated by backend
      projectId: selectedProjectId,
      productId: variant.productId,
      energyLevel: variant.energyLevel,
      capacityCode: variant.capacityCode,
      decorationAdjustments: [],
      createdAt: '',
      updatedAt: '',
    };

    setCurrentConfig(newConfig);
    resetHistory(newConfig);
    setHasUnsavedChanges(false);
    setSelectedLayerId(null);
  };

  const handleLayerChange = (layerId: string, changes: { x: number; y: number }) => {
    if (!currentConfig) return;

    // Parse layerId to get decorationId (format: deco-{id})
    if (!layerId.startsWith('deco-')) return;
    const decorationId = layerId.replace('deco-', '');

    // Select the layer being moved
    setSelectedLayerId(layerId);

    const adjustments = [...(currentConfig.decorationAdjustments || [])];
    const index = adjustments.findIndex(a => a.decorationId === decorationId);
    
    if (index !== -1) {
      adjustments[index] = { ...adjustments[index], offsetX: changes.x, offsetY: changes.y };
    } else {
      adjustments.push({ decorationId, offsetX: changes.x, offsetY: changes.y });
    }

    setCurrentConfig({ ...currentConfig, decorationAdjustments: adjustments });
    setHasUnsavedChanges(true);
  };

  const handleSave = async () => {
    if (!currentConfig) return;
    try {
      await upsertInstance(currentConfig);
      message.success('Instance configuration saved');
      setHasUnsavedChanges(false);
    } catch (error) {
      message.error('Failed to save configuration');
    }
  };

  const handleResetAdjustment = (decorationId: string) => {
    if (!currentConfig) return;
    const adjustments = (currentConfig.decorationAdjustments || []).filter(a => a.decorationId !== decorationId);
    setCurrentConfig({ ...currentConfig, decorationAdjustments: adjustments });
    setHasUnsavedChanges(true);
  };

  // Helper to generate unique key for Select Option
  const getVariantKey = (v: CompositionInput) => 
    `${v.productId}-${v.energyLevel || 'N/A'}-${v.capacityCode || 'N/A'}`;

  const selectedVariant = useMemo(() => 
    generatedVariants.find(v => getVariantKey(v) === selectedVariantKey),
  [generatedVariants, selectedVariantKey]);

  // Compute layers for current view
  const layers = useMemo(() => {
    if (!selectedVariant || !currentConfig) return [];
    const product = products.find(p => p.id === selectedVariant.productId);
    if (!product) return [];

    return computeLayers(
      product, 
      decorations, 
      selectedVariant, 
      currentProject?.template,
      currentConfig
    );
  }, [selectedVariant, currentConfig, products, decorations, currentProject]);

  // Filter only decoration layers for the sidebar list
  const decorationLayers = useMemo(() => 
    layers.filter(l => {
      // Include both 'decoration' and 'background' types if they are images and have IDs starting with 'deco-'
      // Based on computeLayers logic, decorations have id `deco-${id}`.
      // Products have `product-${id}`.
      return l.id.startsWith('deco-');
    })
  , [layers]);

  // Also include Product layer in the list?
  // User asked: "Why can't I select the product image?"
  // So we should include ALL layers in the sidebar list, or at least Product + Decorations.
  const interactiveLayers = useMemo(() => 
    layers.filter(l => l.type === 'image') // Include all image layers (Product + Decorations)
  , [layers]);

  if (!selectedProjectId) {
    return <Empty description="Please select a project first" />;
  }

  if (generatedVariants.length === 0) {
    return <Empty description="Please generate variants in Configuration tab first" />;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <Card title="Instance Fine-Tuner">
        <Row gutter={24} align="middle">
          <Col span={12}>
            <Select
              style={{ width: '100%' }}
              placeholder="Select a variant to edit"
              onChange={handleVariantSelect}
              value={selectedVariantKey}
            >
              {generatedVariants.map(v => {
                const p = products.find(prod => prod.id === v.productId);
                return (
                  <Option key={getVariantKey(v)} value={getVariantKey(v)}>
                    {p?.meta.series} - {v.energyLevel} - {v.capacityCode}
                  </Option>
                );
              })}
            </Select>
          </Col>
          <Col span={12} style={{ textAlign: 'right' }}>
            <div style={{ display: 'flex', gap: 8, justifyContent: 'flex-end' }}>
                <Tooltip title="Undo (Ctrl+Z)">
                    <Button icon={<UndoOutlined />} disabled={!canUndo} onClick={undo} />
                </Tooltip>
                <Tooltip title="Redo (Ctrl+Shift+Z)">
                    <Button icon={<RedoOutlined />} disabled={!canRedo} onClick={redo} />
                </Tooltip>
                <Button 
                type="primary" 
                icon={<SaveOutlined />} 
                onClick={handleSave}
                disabled={!hasUnsavedChanges}
                loading={loading}
                >
                Save Changes
                </Button>
            </div>
          </Col>
        </Row>
      </Card>

      {selectedVariant && currentProject && (
        <div style={{ display: 'flex', gap: '24px' }}>
          {/* Left: Layer List Sidebar */}
          <div style={{ width: 250 }}>
             <Card 
                title="Layers" 
                size="small"
                bodyStyle={{ padding: 0, maxHeight: 600, overflowY: 'auto' }}
             >
                <List
                    size="small"
                    dataSource={[...interactiveLayers].reverse()} // Show top layers first
                    renderItem={(item) => {
                        const isProduct = item.id.startsWith('product-');
                        const decoId = isProduct ? '' : item.id.replace('deco-', '');
                        
                        const adjustment = !isProduct && currentConfig?.decorationAdjustments?.find(a => a.decorationId === decoId);
                        const isAdjusted = !!adjustment;
                        const isSelected = selectedLayerId === item.id;
                        
                        // Find asset name
                        let name = item.id;
                        if (isProduct) {
                            const prod = products.find(p => p.id === item.assetId);
                            name = prod ? `Product: ${prod.meta.series}` : 'Product Layer';
                        } else {
                            const asset = decorations.find(d => d.id === decoId);
                            name = asset ? `${asset.meta.category} (${decoId.slice(-4)})` : decoId;
                        }

                        return (
                            <List.Item 
                                onClick={() => setSelectedLayerId(item.id)}
                                style={{ 
                                    cursor: 'pointer',
                                    background: isSelected ? '#e6f7ff' : 'transparent',
                                    borderLeft: isSelected ? '3px solid #1890ff' : '3px solid transparent'
                                }}
                                actions={[
                                    isAdjusted && (
                                        <Tooltip title="Reset Position">
                                            <Button 
                                                type="text" 
                                                size="small" 
                                                icon={<DeleteOutlined />} 
                                                onClick={(e) => {
                                                    e.stopPropagation();
                                                    if (!isProduct) handleResetAdjustment(decoId);
                                                }}
                                            />
                                        </Tooltip>
                                    )
                                ]}
                            >
                                <List.Item.Meta
                                    title={<Text style={{ fontSize: 13 }}>{name}</Text>}
                                    description={
                                        <div style={{ fontSize: 11 }}>
                                            Z: {item.zIndex}
                                            {isAdjusted && <Tag color="orange" style={{ marginLeft: 8, transform: 'scale(0.8)' }}>Modified</Tag>}
                                        </div>
                                    }
                                />
                            </List.Item>
                        );
                    }}
                />
             </Card>
          </div>

          {/* Center: Canvas */}
          <div style={{ width: 600 }}>
            <Card title="Interactive Preview" bodyStyle={{ padding: 0 }}>
              <div style={{ overflow: 'hidden', background: '#f0f0f0', display: 'flex', justifyContent: 'center' }}>
                <InteractiveCanvas
                  width={currentProject.canvasWidth}
                  height={currentProject.canvasHeight}
                  scale={0.5} 
                  layers={layers}
                  onLayerChange={handleLayerChange}
                  selectedLayerId={selectedLayerId} // Pass selection to canvas
                />
              </div>
            </Card>
            <div style={{ marginTop: 8, textAlign: 'center' }}>
                <Text type="secondary" style={{ fontSize: 12 }}>
                    Tip: Select layer from left sidebar or click on canvas. Use Ctrl+Z to undo.
                </Text>
            </div>
          </div>
          
          {/* Right: Properties */}
          <div style={{ flex: 1 }}>
            <Card title="Properties">
              {!selectedLayerId ? (
                <Empty description="Select a layer to view properties" image={Empty.PRESENTED_IMAGE_SIMPLE} />
              ) : (
                (() => {
                    const layer = layers.find(l => l.id === selectedLayerId);
                    if (!layer) return <Empty description="Layer not found" />;
                    
                    const isProduct = layer.id.startsWith('product-');
                    const decoId = isProduct ? '' : layer.id.replace('deco-', '');
                    const adj = !isProduct ? currentConfig?.decorationAdjustments?.find(a => a.decorationId === decoId) : undefined;
                    
                    return (
                        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                            <div>
                                <Text type="secondary">Layer ID</Text>
                                <div><Text code>{layer.id}</Text></div>
                            </div>
                            <div>
                                <Text type="secondary">Current Position</Text>
                                <div style={{ display: 'flex', gap: 16, marginTop: 4 }}>
                                    <Tag>X: {Math.round(layer.x || 0)}</Tag>
                                    <Tag>Y: {Math.round(layer.y || 0)}</Tag>
                                </div>
                            </div>
                            {!isProduct && (
                                <div>
                                    <Text type="secondary">Adjustment Offset</Text>
                                    <div style={{ display: 'flex', gap: 16, marginTop: 4 }}>
                                        <Tag color={adj ? 'blue' : 'default'}>dX: {Math.round(adj?.offsetX || 0)}</Tag>
                                        <Tag color={adj ? 'blue' : 'default'}>dY: {Math.round(adj?.offsetY || 0)}</Tag>
                                    </div>
                                </div>
                            )}
                            {adj && !isProduct && (
                                <Button danger onClick={() => handleResetAdjustment(decoId)}>
                                    Reset Position
                                </Button>
                            )}
                            {isProduct && (
                                <Text type="secondary" style={{ fontSize: 12 }}>
                                    Product layer position is fixed by template.
                                </Text>
                            )}
                        </div>
                    );
                })()
              )}
            </Card>
          </div>
        </div>
      )}
    </div>
  );
};
