import React, { useState, useEffect, useMemo } from 'react';
import { Card, Select, Button, Row, Col, Typography, message, Empty, Spin } from 'antd';
import { SaveOutlined } from '@ant-design/icons';
import { useCompositionStore } from '../../stores/useCompositionStore';
import { useAssetStore } from '../../stores/useAssetStore';
import { useProjectStore } from '../../stores/useProjectStore';
import { useInstanceStore } from '../../stores/useInstanceStore';
import { computeLayers } from '../../utils/layerMatcher';
import { InteractiveCanvas } from './InteractiveCanvas';
import { InstanceConfig, CompositionInput } from '@ac-gen/shared';

const { Title, Text } = Typography;
const { Option } = Select;

export const InstanceFineTuner: React.FC = () => {
  const { generatedVariants, selectedProjectId } = useCompositionStore();
  const { products, decorations } = useAssetStore();
  const { projects } = useProjectStore();
  const { instances, fetchInstances, upsertInstance, loading } = useInstanceStore();

  const [selectedVariantKey, setSelectedVariantKey] = useState<string | null>(null);
  const [currentConfig, setCurrentConfig] = useState<InstanceConfig | null>(null);
  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);

  const currentProject = useMemo(() => 
    projects.find(p => p.id === selectedProjectId), 
  [projects, selectedProjectId]);

  useEffect(() => {
    if (selectedProjectId) {
      fetchInstances(selectedProjectId);
    }
  }, [selectedProjectId, fetchInstances]);

  // Handle Variant Selection
  const handleVariantSelect = (key: string) => {
    setSelectedVariantKey(key);
    const variant = generatedVariants.find(v => getVariantKey(v) === key);
    if (!variant || !selectedProjectId) return;

    // Find existing config or create new draft
    const existing = instances.find(i => 
      i.projectId === selectedProjectId &&
      i.productId === variant.productId &&
      i.energyLevel === variant.energyLevel &&
      i.capacityCode === variant.capacityCode
    );

    if (existing) {
      setCurrentConfig(existing);
    } else {
      setCurrentConfig({
        id: '', // Will be generated by backend
        projectId: selectedProjectId,
        productId: variant.productId,
        energyLevel: variant.energyLevel,
        capacityCode: variant.capacityCode,
        decorationAdjustments: [],
        createdAt: '',
        updatedAt: '',
      });
    }
    setHasUnsavedChanges(false);
  };

  const handleLayerChange = (layerId: string, changes: { x: number; y: number }) => {
    if (!currentConfig) return;

    // Parse layerId to get decorationId (format: deco-{id})
    if (!layerId.startsWith('deco-')) return;
    const decorationId = layerId.replace('deco-', '');

    console.log('FineTuner: Layer Changed', { layerId, decorationId, changes });

    setCurrentConfig(prev => {
      if (!prev) return null;
      
      const adjustments = [...(prev.decorationAdjustments || [])];
      const index = adjustments.findIndex(a => a.decorationId === decorationId);
      
      if (index !== -1) {
        adjustments[index] = { ...adjustments[index], offsetX: changes.x, offsetY: changes.y };
      } else {
        adjustments.push({ decorationId, offsetX: changes.x, offsetY: changes.y });
      }

      return { ...prev, decorationAdjustments: adjustments };
    });
    setHasUnsavedChanges(true);
  };

  const handleSave = async () => {
    if (!currentConfig) return;
    try {
      await upsertInstance(currentConfig);
      message.success('Instance configuration saved');
      setHasUnsavedChanges(false);
    } catch (error) {
      message.error('Failed to save configuration');
    }
  };

  // Helper to generate unique key for Select Option
  const getVariantKey = (v: CompositionInput) => 
    `${v.productId}-${v.energyLevel || 'N/A'}-${v.capacityCode || 'N/A'}`;

  const selectedVariant = useMemo(() => 
    generatedVariants.find(v => getVariantKey(v) === selectedVariantKey),
  [generatedVariants, selectedVariantKey]);

  // Compute layers for current view
  const layers = useMemo(() => {
    if (!selectedVariant || !currentConfig) return [];
    const product = products.find(p => p.id === selectedVariant.productId);
    if (!product) return [];

    return computeLayers(
      product, 
      decorations, 
      selectedVariant, 
      currentProject?.template,
      currentConfig
    );
  }, [selectedVariant, currentConfig, products, decorations, currentProject]);

  if (!selectedProjectId) {
    return <Empty description="Please select a project first" />;
  }

  if (generatedVariants.length === 0) {
    return <Empty description="Please generate variants in Configuration tab first" />;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <Card title="Instance Fine-Tuner">
        <Row gutter={24} align="middle">
          <Col span={12}>
            <Select
              style={{ width: '100%' }}
              placeholder="Select a variant to edit"
              onChange={handleVariantSelect}
              value={selectedVariantKey}
            >
              {generatedVariants.map(v => {
                const p = products.find(prod => prod.id === v.productId);
                return (
                  <Option key={getVariantKey(v)} value={getVariantKey(v)}>
                    {p?.meta.series} - {v.energyLevel} - {v.capacityCode}
                  </Option>
                );
              })}
            </Select>
          </Col>
          <Col span={12} style={{ textAlign: 'right' }}>
            <Button 
              type="primary" 
              icon={<SaveOutlined />} 
              onClick={handleSave}
              disabled={!hasUnsavedChanges}
              loading={loading}
            >
              Save Changes
            </Button>
          </Col>
        </Row>
      </Card>

      {selectedVariant && currentProject && (
        <div style={{ display: 'flex', gap: '24px' }}>
          <div style={{ width: 600 }}>
            <Card title="Interactive Preview (Drag decorations to move)">
              <div style={{ overflow: 'hidden' }}>
                <InteractiveCanvas
                  width={currentProject.canvasWidth}
                  height={currentProject.canvasHeight}
                  scale={0.5} // Scale down to fit 600px width (approx)
                  layers={layers}
                  onLayerChange={handleLayerChange}
                />
              </div>
            </Card>
          </div>
          
          <div style={{ flex: 1 }}>
            <Card title="Adjustments">
              {currentConfig?.decorationAdjustments?.length === 0 ? (
                <Text type="secondary">No adjustments made yet.</Text>
              ) : (
                <ul style={{ paddingLeft: 20 }}>
                  {currentConfig?.decorationAdjustments?.map(adj => {
                    const deco = decorations.find(d => d.id === adj.decorationId);
                    const name = deco ? `${deco.meta.category} (${deco.id.slice(-4)})` : adj.decorationId;
                    return (
                        <li key={adj.decorationId} style={{ marginBottom: 4 }}>
                        <Text strong>{name}</Text>: X={Math.round(adj.offsetX)}, Y={Math.round(adj.offsetY)}
                        </li>
                    );
                  })}
                </ul>
              )}
            </Card>
          </div>
        </div>
      )}
    </div>
  );
};
